// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAAoqSF42wKBjXMLEjHLCixwuQAsZnrqLQ",
    authDomain: "test-3fbc1.firebaseapp.com",
    databaseURL: "https://test-3fbc1-default-rtdb.firebaseio.com",
    projectId: "test-3fbc1",
    storageBucket: "test-3fbc1.appspot.com",
    messagingSenderId: "429153088555",
    appId: "1:429153088555:web:a81e657e484b00d157a66e",
    measurementId: "G-8Q9ES5P84T",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgGRQHKdj7kWqgv4Se4RvjSwqI9znZywk',
    appId: '1:429153088555:android:f0e47817a4ecaa9c57a66e',
    messagingSenderId: '429153088555',
    projectId: 'test-3fbc1',
    storageBucket: 'test-3fbc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApUN-2eGcxeSnfhESv0bqRnBCDfvOBQ3Q',
    appId: '1:429153088555:ios:d67727ad269bdd5e57a66e',
    messagingSenderId: '429153088555',
    projectId: 'test-3fbc1',
    storageBucket: 'test-3fbc1.appspot.com',
    androidClientId:
        '429153088555-n4rbc2vfar8vkvl18utupvm42v5ag3st.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApUN-2eGcxeSnfhESv0bqRnBCDfvOBQ3Q',
    appId: '1:429153088555:ios:d67727ad269bdd5e57a66e',
    messagingSenderId: '429153088555',
    projectId: 'test-3fbc1',
    storageBucket: 'test-3fbc1.appspot.com',
    androidClientId:
        '429153088555-n4rbc2vfar8vkvl18utupvm42v5ag3st.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAoqSF42wKBjXMLEjHLCixwuQAsZnrqLQ',
    appId: '1:429153088555:web:ab9c3bb88021500357a66e',
    messagingSenderId: '429153088555',
    projectId: 'test-3fbc1',
    authDomain: 'test-3fbc1.firebaseapp.com',
    storageBucket: 'test-3fbc1.appspot.com',
    measurementId: 'G-FWR8JM4FLZ',
  );
}
